name: glibc-builder
on:
  push:
    branches:
      - master

jobs:
  glibc-builder:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    container:
      image: ubuntu:latest
      env:
        GLIBC_VER: '2.31'
        PREFIX_DIR: '/usr/glibc-compat'
        DEBIAN_FRONTEND: 'noninteractive'
    steps:
      - name: clone
        uses: actions/checkout@master
      - name: update container
        run: apt-get update
      - name: install packages
        run: apt-get -y install build-essential wget gawk bison python3 gettext texinfo
      - name: start build
        run: |
          chmod 755 build.sh
          ./build.sh
      - name: echo
        run: ls -al
