name: glibc-builder
on:
  push:
    branches:
      - master

jobs:
  glibc-builder:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
      env:
        GLIBC_VER: '2.31'
        PREFIX_DIR: '/usr/glibc-compat'
        DEBIAN_FRONTEND: 'noninteractive'
    steps:
      - name: clone
        uses: actions/checkout@master
      - name: update container
        shell: bash
        run: apt-get update
      - name: install packages
        shell: bash
        run: apt-get -y install build-essential wget gawk bison python3 gettext texinfo
      - name: echo pwd
        shell: bash
        run: echo "$GITHUB_WORKSPACE"
#      - name: start build
#        shell: bash
#        run: |
#          chmod 755 build.sh
#          ./build.sh
