name: glibc build
on:
  push:
    branches:
      - master

jobs:
  glibc:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    env:
      GLIBC_VER: '2.31'
      PREFIX_DIR: '/usr/glibc-compat'
    steps:
      - name: clone
        uses: actions/checkout@master
      - name: update and install packages
        shell: bash
        run: |
          apt-get update
          apt-get -y install bison