name: glibc-apk
on:
  push:
    branches:
      - master

env:
  GLIBC_VER: '2.31'

jobs:
  apk-build:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@master
      - name: start build
        uses: triptixx/action-alpine-abuild@master
        with:
          packager: 'Loxoo Labs <triptixx@loxoolabs.net>'
