name: glibc-builder
on:
  push:
    branches:
      - master

jobs:
  glibc-builder:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
      env:
        GLIBC_VER: '2.31'
        PREFIX_DIR: '/usr/glibc-compat'
    steps:
      - name: clone
        uses: actions/checkout@master
      - name: start build.sh
        shell: bash
        run: |
          pwd
          ls -al
          chmod 755 build.sh
          ./build.sh